### ISSUE TITLE
Simplify code

### ISSUE THREAD

**Issue by libary** [torhovland/flatware#2]
Hello! It is very interesting. But I think that this code:
`<button @onclick(() => DispatchAsync(MyMsg.NewIncrement(3)))>Click me</button>`
`<p>Current count: @Mdl.Count</p>`
looks somewhat more rude than the original code:
`<button @onclick(IncrementCount)>Click me</button>`
`<p>Current count: @Count</p>`
Would it be possible to simplify the syntax?
Thanks!

**Comment by torhovland** [comment]
Hi!

Unfortunately, I don't see how we can simplify that, except maybe renaming `DispatchAsync` to `Dispatch` or something even shorter.

Remember that the original code also has a block where `IncrementCount` is defined, so the comparison isn't entirely fair.

**Comment by libary** [comment]
I'm sure you'll think of something. I will attend!)

**Comment by torhovland** [comment]
Also keep in mind that the original code isn't passing a parameter. If you wanted similar behavior, you would have to do:

```
<button @onclick(() => IncrementCount(3))>Click me</button>
```
