### ISSUE TITLE
Server-side Razor and Client-side Razor mix

### ISSUE THREAD

**Issue by libary** [torhovland/flatware#4]
Is it possible to mix these technologies on any one page?

**Comment by torhovland** [comment]
Depends what you mean. It is certainly possible to have a Razor page running on the backend, with a blazor-boot script tag and a div that is meant for Blazor to render its pages/components into.

If you mean to use the same cshtml for server-side rendering with Razor and then letting Blazor take over and render the same cshtml after Mono has loaded, that will not work at this point, but I'm sure Microsoft is considering something like this for the future.
